## You can test the result by running:
## SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l
## References: https://developer.1password.com/docs/ssh/agent/config

[[ssh-keys]]
item = "4tj53fcjqro33pj7iosnnyplga"
vault = "work-academia"
