## {{{1 prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind-key C-z last-window
## }}}1

## {{{1 appearance
set-option -g status-position top
## }}}1

## {{{1 mouse and keyboard
set-option -g mouse on
set-window-option -g mode-keys vi
## }}}1
