## You can test the result by running:
## SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ssh-add -l
## References: https://developer.1password.com/docs/ssh/agent/config

[[ssh-keys]]
item = "7izb2wrtxn6ub5mvi3lakp7rrq"
vault = "limakzi"

[[ssh-keys]]
item = "ovzptdktu4yozbkjo24t3wgkzq"
vault = "limakzi"
