"$schema" = 'https://starship.rs/config-schema.json'

format = """$all"""

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[λ](bold #50fa7b)"
error_symbol = "[λ](bold #ff5555)"

[directory]
truncation_length = 2

[cmd_duration]
disabled = true

[git_branch]
only_attached = true

[git_metrics]
disabled = true

[git_status]
disabled = true

[hostname]
ssh_symbol = ' '

[username]
disabled = true

[lua]
disabled = true

[package]
disabled = false

[azure]
disabled = false

[aws]
disabled = false
