---

name: dotbot
run-name: dotbot-${{ github.event.number }} ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [ "main" ]

jobs:
  dotbot:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        - 'dotbot.linux.conf.yaml'
        - 'dotbot.macos.conf.yaml'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: true

      - name: Run dotbot 
        run: dotbot -c dotbot.conf.yaml
