---

name: dotbot
run-name: dotbot-${{ github.event.number }} ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [ "main" ]

jobs:
  dotbot:
    runs-on: ubuntu-24.04
    steps:
      - name: git -- checkout
        uses: actions/checkout@v4

      - name: python -- setup
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: python -- install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: true

      - name: dotbot -- apply
        run: dotbot -c dotbot.conf.yaml
