---

name: dotbot
run-name: dotbot-${{ github.event.number }} ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [ "**" ]

jobs:
  dotbot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            dotbot-config: 'dotbot.macos.conf.yaml'
          - os: ubuntu-latest
            dotbot-config: 'dotbot.linux.conf.yaml'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: true

      - name: Run dotbot 
        working-directory: src
        run: dotbot -c ${{ matrix.dotbot-config }}
