---
name: Release - draft release-notes
run-name: release-draft-${{ github.event.number }}

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: config.release-drafter.yaml
          tag: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
          publish: ${{ github.ref_type == 'tag' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
